#!/usr/bin/env zsh

script_dir="${0:A:h}"
root="${script_dir:h}"
if [[ "${1:-}" == --version ]]; then
  version=unknown
  [[ -r "${root}/VERSION" ]] && version="$(<"${root}/VERSION")"
  print -r -- "ii-tmux-popup $version"
  exit
fi
if [[ ! -o interactive && -t 0 ]]; then
  exec zsh -f -i "$0" "$@"
fi
II_TMUX_INTEGRATION=0 II_GO_ROOT="$root" source "${root}/ii.plugin.zsh" || exit
ii_zsh_tmux_popup "$@"
