#!/usr/bin/env zsh

script_dir="${0:A:h}"
if [[ "${1:-}" == "--version" ]]; then
  version_file="${script_dir:h}/VERSION"
  if [[ -r "$version_file" ]]; then
    print "ii-tmux-pice $(<"$version_file")"
  else
    print "ii-tmux-pice unknown"
  fi
  exit
fi
exec zsh "${script_dir}/ii-tmux-input" copy-execute "$@"
