#!/usr/bin/env zsh

script_dir="${0:A:h}"
zsh_root="${script_dir:h}"
if [[ -r "${zsh_root}/RELEASE" ]]; then
  root="$zsh_root"
else
  root="${zsh_root:h:h}"
fi
if [[ "${1:-}" == --version ]]; then
  version=unknown
  [[ -r "${root}/VERSION" ]] && version="$(<"${root}/VERSION")"
  print -r -- "ii-tmux-popup $version"
  exit
fi
if [[ ! -o interactive && -t 0 ]]; then
  exec zsh -f -i "$0" "$@"
fi
II_TMUX_INTEGRATION=0 II_ROOT="$root" source "${zsh_root}/ii.plugin.zsh" || exit
ii_zsh_tmux_popup "$@"
